/****************************************************************
*								*
*	Copyright 2013 Fidelity Information Services, Inc	*
*								*
*	This source code contains the intellectual property	*
*	of its copyright holder(s), and is made available	*
*	under a license.  If you do not know the terms of	*
*	the license, please stop and do not read further.	*
*								*
****************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fis_gtm_ji_GTMCI */

#ifndef _Included_com_fis_gtm_ji_GTMCI
#define _Included_com_fis_gtm_ji_GTMCI
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: gtmThread */
/* Inaccessible static: isInitDone */
/*
 * Class:     com_fis_gtm_ji_GTMCI
 * Method:    doVoidCallin
 * Signature: (Ljava/lang/String;[Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_fis_gtm_ji_GTMCI_doVoidCallin
  (JNIEnv *, jclass, jstring, jobjectArray);

/*
 * Class:     com_fis_gtm_ji_GTMCI
 * Method:    doBooleanCallin
 * Signature: (Ljava/lang/String;[Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_fis_gtm_ji_GTMCI_doBooleanCallin
  (JNIEnv *, jclass, jstring, jobjectArray);

/*
 * Class:     com_fis_gtm_ji_GTMCI
 * Method:    doIntCallin
 * Signature: (Ljava/lang/String;[Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_fis_gtm_ji_GTMCI_doIntCallin
  (JNIEnv *, jclass, jstring, jobjectArray);

/*
 * Class:     com_fis_gtm_ji_GTMCI
 * Method:    doLongCallin
 * Signature: (Ljava/lang/String;[Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_com_fis_gtm_ji_GTMCI_doLongCallin
  (JNIEnv *, jclass, jstring, jobjectArray);

/*
 * Class:     com_fis_gtm_ji_GTMCI
 * Method:    doFloatCallin
 * Signature: (Ljava/lang/String;[Ljava/lang/Object;)F
 */
JNIEXPORT jfloat JNICALL Java_com_fis_gtm_ji_GTMCI_doFloatCallin
  (JNIEnv *, jclass, jstring, jobjectArray);

/*
 * Class:     com_fis_gtm_ji_GTMCI
 * Method:    doDoubleCallin
 * Signature: (Ljava/lang/String;[Ljava/lang/Object;)D
 */
JNIEXPORT jdouble JNICALL Java_com_fis_gtm_ji_GTMCI_doDoubleCallin
  (JNIEnv *, jclass, jstring, jobjectArray);

/*
 * Class:     com_fis_gtm_ji_GTMCI
 * Method:    doStringCallin
 * Signature: (Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fis_gtm_ji_GTMCI_doStringCallin
  (JNIEnv *, jclass, jstring, jobjectArray);

/*
 * Class:     com_fis_gtm_ji_GTMCI
 * Method:    doByteArrayCallin
 * Signature: (Ljava/lang/String;[Ljava/lang/Object;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_fis_gtm_ji_GTMCI_doByteArrayCallin
  (JNIEnv *, jclass, jstring, jobjectArray);

/*
 * Class:     com_fis_gtm_ji_GTMCI
 * Method:    doInit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_fis_gtm_ji_GTMCI_doInit
  (JNIEnv *, jclass);

/*
 * Class:     com_fis_gtm_ji_GTMCI
 * Method:    doShutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fis_gtm_ji_GTMCI_doShutdown
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
